/**
 * This file contains content generated by AI.
 * AI-generated contents are not applicable for copyright nor warranty.
 */
package top.niunaijun.blackbox.utils;

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

/**
 * Manager for storing and retrieving per-app ABI preferences (Java version for Bcore)
 * 
 * When user selects a specific ABI for an app, it will be used when:
 * - Installing the app (copying native libraries)
 * - Reinstalling the app
 * 
 * If the selected ABI matches the host device ABI, it runs natively.
 * If not, QEMU emulation is used (if available).
 */
public class AbiPreferenceHelper {
    private static final String PREF_NAME = "AbiPreferences";
    private static final String TAG = "AbiPreferenceHelper";
    private static SharedPreferences prefs = null;
    
    private static synchronized SharedPreferences getPrefs(Context context) {
        if (prefs == null) {
            prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE);
        }
        return prefs;
    }
    
    /**
     * Get the preferred ABI for a package
     * @param context The context
     * @param packageName The package name
     * @return The preferred ABI, or null if no preference is set
     */
    public static String getPreferredAbi(Context context, String packageName) {
        try {
            return getPrefs(context).getString(packageName, null);
        } catch (Exception e) {
            Log.w(TAG, "Failed to get preferred ABI for " + packageName + ": " + e.getMessage());
            return null;
        }
    }
    
    /**
     * Check if a package has a preferred ABI set
     * @param context The context
     * @param packageName The package name
     * @return true if a preference is set
     */
    public static boolean hasPreference(Context context, String packageName) {
        try {
            return getPrefs(context).contains(packageName);
        } catch (Exception e) {
            Log.w(TAG, "Failed to check preference for " + packageName + ": " + e.getMessage());
            return false;
        }
    }
}
