/**
 * This file contains content generated by AI.
 * AI-generated contents are not applicable for copyright nor warranty.
 */
package top.niunaijun.blackboxa.util

import android.content.Context
import android.content.SharedPreferences
import top.niunaijun.blackboxa.app.App

/**
 * Manager for storing and retrieving per-app ABI preferences
 * 
 * When user selects a specific ABI for an app, it will be used when:
 * - Installing the app (copying native libraries)
 * - Reinstalling the app
 * 
 * If the selected ABI matches the host device ABI, it runs natively.
 * If not, QEMU emulation is used (if available).
 */
object AbiPreferenceManager {
    private const val PREF_NAME = "AbiPreferences"
    private const val TAG = "AbiPreferenceManager"
    
    private val prefs: SharedPreferences by lazy {
        App.getContext().getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
    }
    
    /**
     * Save the preferred ABI for a package
     * @param packageName The package name
     * @param abi The preferred ABI (e.g., "arm64-v8a", "armeabi-v7a", "x86_64", "x86")
     */
    fun setPreferredAbi(packageName: String, abi: String) {
        prefs.edit().putString(packageName, abi).apply()
        android.util.Log.d(TAG, "Set preferred ABI for $packageName: $abi")
    }
    
    /**
     * Get the preferred ABI for a package
     * @param packageName The package name
     * @return The preferred ABI, or null if no preference is set
     */
    fun getPreferredAbi(packageName: String): String? {
        return prefs.getString(packageName, null)
    }
    
    /**
     * Clear the ABI preference for a package
     * @param packageName The package name
     */
    fun clearPreferredAbi(packageName: String) {
        prefs.edit().remove(packageName).apply()
        android.util.Log.d(TAG, "Cleared preferred ABI for $packageName")
    }
    
    /**
     * Clear all ABI preferences
     */
    fun clearAll() {
        prefs.edit().clear().apply()
        android.util.Log.d(TAG, "Cleared all ABI preferences")
    }
    
    /**
     * Check if a package has a preferred ABI set
     * @param packageName The package name
     * @return true if a preference is set
     */
    fun hasPreference(packageName: String): Boolean {
        return prefs.contains(packageName)
    }
}
