#!/bin/bash
# This file contains content generated by AI.
# AI-generated contents are not applicable for copyright nor warranty.

echo "Downloading QEMU user-mode static binaries and Android runtime libraries..."
echo "Shirobako - Fork of BlackBox"
echo ""

# Create directories for all architectures
ASSETS_DIR="Bcore/src/main/assets"

# QEMU directories for different host architectures
mkdir -p "$ASSETS_DIR/qemu/arm64-v8a"      # aarch64 host
mkdir -p "$ASSETS_DIR/qemu/armeabi-v7a"    # arm host
mkdir -p "$ASSETS_DIR/qemu/x86_64"         # x86_64 host
mkdir -p "$ASSETS_DIR/qemu/x86"            # i386 host

# Runtime directories for different guest architectures  
mkdir -p "$ASSETS_DIR/runtime/arm64-v8a"   # aarch64 guest
mkdir -p "$ASSETS_DIR/runtime/armeabi-v7a" # arm guest
mkdir -p "$ASSETS_DIR/runtime/x86_64"      # x86_64 guest
mkdir -p "$ASSETS_DIR/runtime/x86"         # i386 guest

# Create temporary directory
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"

echo "Working in temporary directory: $TEMP_DIR"

# GitHub release URL for vendored assets
RELEASE_URL="https://github.com/cyanmint/shirobako/releases/download/main"

###############################
# Download vendored QEMU binaries
###############################

echo ""
echo "Downloading vendored QEMU binaries from GitHub release..."
echo "Architecture support matrix:"
echo "  - arm host: arm natively, i386 via QEMU"
echo "  - i386 host: i386 natively, arm via QEMU"
echo "  - aarch64 host: aarch64 natively, x86_64/i386/arm via QEMU"
echo "  - x86_64 host: x86_64 natively, aarch64/arm/i386 via QEMU"
echo ""

# For aarch64 (arm64-v8a) host
echo "Downloading QEMU binaries for aarch64 host..."

if wget -q "${RELEASE_URL}/aarch64-qemu-arm" -O aarch64-qemu-arm; then
    chmod +x aarch64-qemu-arm
    cp aarch64-qemu-arm "$OLDPWD/$ASSETS_DIR/qemu/arm64-v8a/qemu-arm-static"
    echo "  ✓ Downloaded aarch64-qemu-arm (arm guest on aarch64 host)"
else
    echo "  ✗ Failed to download aarch64-qemu-arm"
fi

if wget -q "${RELEASE_URL}/aarch64-qemu-i386" -O aarch64-qemu-i386; then
    chmod +x aarch64-qemu-i386
    cp aarch64-qemu-i386 "$OLDPWD/$ASSETS_DIR/qemu/arm64-v8a/qemu-i386-static"
    echo "  ✓ Downloaded aarch64-qemu-i386 (i386 guest on aarch64 host)"
else
    echo "  ✗ Failed to download aarch64-qemu-i386"
fi

if wget -q "${RELEASE_URL}/aarch64-qemu-x86_64" -O aarch64-qemu-x86_64; then
    chmod +x aarch64-qemu-x86_64
    cp aarch64-qemu-x86_64 "$OLDPWD/$ASSETS_DIR/qemu/arm64-v8a/qemu-x86_64-static"
    echo "  ✓ Downloaded aarch64-qemu-x86_64 (x86_64 guest on aarch64 host)"
else
    echo "  ✗ Failed to download aarch64-qemu-x86_64"
fi

# For arm (armeabi-v7a) host
echo ""
echo "Downloading QEMU binaries for arm host..."

if wget -q "${RELEASE_URL}/arm-qemu-i386" -O arm-qemu-i386; then
    chmod +x arm-qemu-i386
    cp arm-qemu-i386 "$OLDPWD/$ASSETS_DIR/qemu/armeabi-v7a/qemu-i386-static"
    echo "  ✓ Downloaded arm-qemu-i386 (i386 guest on arm host)"
else
    echo "  ✗ Failed to download arm-qemu-i386"
fi

# For x86_64 host
echo ""
echo "Downloading QEMU binaries for x86_64 host..."

if wget -q "${RELEASE_URL}/x86_64-qemu-aarch64" -O x86_64-qemu-aarch64; then
    chmod +x x86_64-qemu-aarch64
    cp x86_64-qemu-aarch64 "$OLDPWD/$ASSETS_DIR/qemu/x86_64/qemu-aarch64-static"
    echo "  ✓ Downloaded x86_64-qemu-aarch64 (aarch64 guest on x86_64 host)"
else
    echo "  ✗ Failed to download x86_64-qemu-aarch64"
fi

if wget -q "${RELEASE_URL}/x86_64-qemu-arm" -O x86_64-qemu-arm; then
    chmod +x x86_64-qemu-arm
    cp x86_64-qemu-arm "$OLDPWD/$ASSETS_DIR/qemu/x86_64/qemu-arm-static"
    echo "  ✓ Downloaded x86_64-qemu-arm (arm guest on x86_64 host)"
else
    echo "  ✗ Failed to download x86_64-qemu-arm"
fi

if wget -q "${RELEASE_URL}/x86_64-qemu-i386" -O x86_64-qemu-i386; then
    chmod +x x86_64-qemu-i386
    cp x86_64-qemu-i386 "$OLDPWD/$ASSETS_DIR/qemu/x86_64/qemu-i386-static"
    echo "  ✓ Downloaded x86_64-qemu-i386 (i386 guest on x86_64 host)"
else
    echo "  ✗ Failed to download x86_64-qemu-i386"
fi

# For i386 (x86) host
echo ""
echo "Downloading QEMU binaries for i386 host..."

if wget -q "${RELEASE_URL}/i386-qemu-arm" -O i386-qemu-arm; then
    chmod +x i386-qemu-arm
    cp i386-qemu-arm "$OLDPWD/$ASSETS_DIR/qemu/x86/qemu-arm-static"
    echo "  ✓ Downloaded i386-qemu-arm (arm guest on i386 host)"
else
    echo "  ✗ Failed to download i386-qemu-arm"
fi

###############################
# Download vendored Android runtime
###############################

echo ""
echo "Downloading vendored Android runtime from GitHub release..."

# Function to extract files from APEX
extract_from_apex() {
    local apex_file=$1
    local output_dir=$2
    local is_64bit=$3
    
    echo "  Extracting runtime files from APEX: $apex_file"
    
    # Unzip the APEX file to get apex_payload.img
    if unzip -q "$apex_file" apex_payload.img -d apex_work; then
        # Use debugfs to extract files from the ext2/4 image
        local payload="apex_work/apex_payload.img"
        
        if [ "$is_64bit" = "true" ]; then
            # Extract 64-bit files
            debugfs -R "dump /bin/linker64 linker64" "$payload" 2>/dev/null && \
                cp linker64 "$output_dir/" && echo "    ✓ Extracted linker64"
            
            # Try different paths for libraries
            debugfs -R "dump /lib64/bionic/libc.so libc.so" "$payload" 2>/dev/null || \
            debugfs -R "dump /lib64/bootstrap/libc.so libc.so" "$payload" 2>/dev/null
            [ -f "libc.so" ] && cp libc.so "$output_dir/" && echo "    ✓ Extracted libc.so"
            
            debugfs -R "dump /lib64/bionic/libm.so libm.so" "$payload" 2>/dev/null || \
            debugfs -R "dump /lib64/bootstrap/libm.so libm.so" "$payload" 2>/dev/null
            [ -f "libm.so" ] && cp libm.so "$output_dir/" && echo "    ✓ Extracted libm.so"
            
            debugfs -R "dump /lib64/bionic/libdl.so libdl.so" "$payload" 2>/dev/null || \
            debugfs -R "dump /lib64/bootstrap/libdl.so libdl.so" "$payload" 2>/dev/null
            [ -f "libdl.so" ] && cp libdl.so "$output_dir/" && echo "    ✓ Extracted libdl.so"
        else
            # Extract 32-bit files
            debugfs -R "dump /bin/linker linker" "$payload" 2>/dev/null && \
                cp linker "$output_dir/" && echo "    ✓ Extracted linker"
            
            # Try different paths for libraries
            debugfs -R "dump /lib/bionic/libc.so libc.so" "$payload" 2>/dev/null || \
            debugfs -R "dump /lib/bootstrap/libc.so libc.so" "$payload" 2>/dev/null
            [ -f "libc.so" ] && cp libc.so "$output_dir/" && echo "    ✓ Extracted libc.so"
            
            debugfs -R "dump /lib/bionic/libm.so libm.so" "$payload" 2>/dev/null || \
            debugfs -R "dump /lib/bootstrap/libm.so libm.so" "$payload" 2>/dev/null
            [ -f "libm.so" ] && cp libm.so "$output_dir/" && echo "    ✓ Extracted libm.so"
            
            debugfs -R "dump /lib/bionic/libdl.so libdl.so" "$payload" 2>/dev/null || \
            debugfs -R "dump /lib/bootstrap/libdl.so libdl.so" "$payload" 2>/dev/null
            [ -f "libdl.so" ] && cp libdl.so "$output_dir/" && echo "    ✓ Extracted libdl.so"
        fi
        
        rm -rf apex_work linker* libc.so libm.so libdl.so
    else
        echo "  ✗ Failed to extract APEX file"
    fi
}

# Download ARM runtime APEX (contains both aarch64 and arm)
echo ""
echo "Downloading ARM Android runtime..."
if wget -q "${RELEASE_URL}/arm+aarch64-com.android.runtime.apex" -O arm-runtime.apex; then
    echo "  ✓ Downloaded arm+aarch64-com.android.runtime.apex"
    
    # Extract 64-bit ARM (aarch64) runtime
    extract_from_apex "arm-runtime.apex" "$OLDPWD/$ASSETS_DIR/runtime/arm64-v8a" "true"
    
    # Extract 32-bit ARM runtime (from /lib directory)
    extract_from_apex "arm-runtime.apex" "$OLDPWD/$ASSETS_DIR/runtime/armeabi-v7a" "false"
    
    rm -f arm-runtime.apex
else
    echo "  ✗ Failed to download arm+aarch64-com.android.runtime.apex"
fi

# Download x86 runtime APEX (contains both x86_64 and i386)
echo ""
echo "Downloading x86 Android runtime..."
if wget -q "${RELEASE_URL}/i386+x86_64-com.android.runtime.apex" -O x86-runtime.apex; then
    echo "  ✓ Downloaded i386+x86_64-com.android.runtime.apex"
    
    # Extract 64-bit x86 (x86_64) runtime
    extract_from_apex "x86-runtime.apex" "$OLDPWD/$ASSETS_DIR/runtime/x86_64" "true"
    
    # Extract 32-bit x86 (i386) runtime (from /lib directory)
    extract_from_apex "x86-runtime.apex" "$OLDPWD/$ASSETS_DIR/runtime/x86" "false"
    
    rm -f x86-runtime.apex
else
    echo "  ✗ Failed to download i386+x86_64-com.android.runtime.apex"
fi

# Return to original directory
cd "$OLDPWD"
rm -rf "$TEMP_DIR"

echo ""
echo "========================================="
echo "Asset download complete!"
echo "========================================="
echo "QEMU binaries downloaded to: $ASSETS_DIR/qemu/"
echo "Runtime libraries downloaded to: $ASSETS_DIR/runtime/"
echo ""

# List what was downloaded
echo "Downloaded QEMU binaries:"
find "$ASSETS_DIR/qemu" -type f -name "qemu-*" -exec ls -lh {} \; 2>/dev/null || echo "  (none found)"

echo ""
echo "Downloaded runtime libraries:"
find "$ASSETS_DIR/runtime" -type f ! -name ".gitkeep" -exec ls -lh {} \; 2>/dev/null || echo "  (none found)"

echo ""
echo "Architecture support:"
echo "  ✓ arm host: native arm, QEMU for i386"
echo "  ✓ i386 host: native i386, QEMU for arm"
echo "  ✓ aarch64 host: native aarch64, QEMU for x86_64/i386/arm"
echo "  ✓ x86_64 host: native x86_64, QEMU for aarch64/arm/i386"
echo ""
echo "APK variants:"
echo "  - shiro.bako (universal): arm, i386, aarch64, x86_64"
echo "  - shiro.bako.lib32 (32-bit): arm, i386"

exit 0
