#!/bin/bash
# This file contains content generated by AI.
# AI-generated contents are not applicable for copyright nor warranty.

set -e

echo "Downloading QEMU user-mode static binaries and Android runtime libraries..."

# Create directories
ASSETS_DIR="Bcore/src/main/assets"
mkdir -p "$ASSETS_DIR/qemu/arm64-v8a"
mkdir -p "$ASSETS_DIR/qemu/armeabi-v7a"
mkdir -p "$ASSETS_DIR/qemu/x86_64"
mkdir -p "$ASSETS_DIR/runtime/arm64-v8a"
mkdir -p "$ASSETS_DIR/runtime/armeabi-v7a"
mkdir -p "$ASSETS_DIR/runtime/x86_64"

# Create temporary directory
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"

echo "Working in temporary directory: $TEMP_DIR"

# QEMU version to download
QEMU_VERSION="8.2.2+ds-1"

###############################
# Download QEMU static binaries
###############################

echo "Downloading QEMU static binaries..."

# For arm64 host
echo "Downloading QEMU for arm64 host..."
wget -q "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_${QEMU_VERSION}_arm64.deb" || \
wget -q "http://deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_${QEMU_VERSION}_arm64.deb"

ar x "qemu-user-static_${QEMU_VERSION}_arm64.deb"
tar xf data.tar.xz
if [ -f "usr/bin/qemu-arm-static" ]; then
    cp usr/bin/qemu-arm-static "$OLDPWD/$ASSETS_DIR/qemu/arm64-v8a/"
    echo "  ✓ Copied qemu-arm-static for arm64 host"
fi
if [ -f "usr/bin/qemu-x86_64-static" ]; then
    cp usr/bin/qemu-x86_64-static "$OLDPWD/$ASSETS_DIR/qemu/arm64-v8a/"
    echo "  ✓ Copied qemu-x86_64-static for arm64 host"
fi
rm -rf usr data.tar.xz control.tar.xz debian-binary "qemu-user-static_${QEMU_VERSION}_arm64.deb"

# For x86_64 host
echo "Downloading QEMU for x86_64 host..."
wget -q "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_${QEMU_VERSION}_amd64.deb" || \
wget -q "http://deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_${QEMU_VERSION}_amd64.deb"

ar x "qemu-user-static_${QEMU_VERSION}_amd64.deb"
tar xf data.tar.xz
if [ -f "usr/bin/qemu-aarch64-static" ]; then
    cp usr/bin/qemu-aarch64-static "$OLDPWD/$ASSETS_DIR/qemu/x86_64/"
    echo "  ✓ Copied qemu-aarch64-static for x86_64 host"
fi
if [ -f "usr/bin/qemu-arm-static" ]; then
    cp usr/bin/qemu-arm-static "$OLDPWD/$ASSETS_DIR/qemu/x86_64/"
    echo "  ✓ Copied qemu-arm-static for x86_64 host"
fi
rm -rf usr data.tar.xz control.tar.xz debian-binary "qemu-user-static_${QEMU_VERSION}_amd64.deb"

# For armeabi-v7a host
echo "Downloading QEMU for armeabi-v7a host..."
wget -q "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_${QEMU_VERSION}_armhf.deb" || \
wget -q "http://deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_${QEMU_VERSION}_armhf.deb"

ar x "qemu-user-static_${QEMU_VERSION}_armhf.deb"
tar xf data.tar.xz
if [ -f "usr/bin/qemu-aarch64-static" ]; then
    cp usr/bin/qemu-aarch64-static "$OLDPWD/$ASSETS_DIR/qemu/armeabi-v7a/"
    echo "  ✓ Copied qemu-aarch64-static for armeabi-v7a host"
fi
if [ -f "usr/bin/qemu-x86_64-static" ]; then
    cp usr/bin/qemu-x86_64-static "$OLDPWD/$ASSETS_DIR/qemu/armeabi-v7a/"
    echo "  ✓ Copied qemu-x86_64-static for armeabi-v7a host"
fi
rm -rf usr data.tar.xz control.tar.xz debian-binary "qemu-user-static_${QEMU_VERSION}_armhf.deb"

###############################
# Download Android runtime from redroid
###############################

echo "Downloading Android runtime from redroid container..."

# Check if docker is available
if ! command -v docker &> /dev/null; then
    echo "Warning: Docker not found, skipping Android runtime download"
    echo "QEMU binaries have been downloaded, but runtime libraries are missing"
    cd "$OLDPWD"
    rm -rf "$TEMP_DIR"
    exit 0
fi

# Pull redroid container
echo "Pulling redroid container (this may take a while)..."
docker pull docker.io/redroid/redroid:16.0.0-latest || {
    echo "Warning: Failed to pull redroid container, skipping runtime download"
    cd "$OLDPWD"
    rm -rf "$TEMP_DIR"
    exit 0
}

# Create temporary container
CONTAINER_ID=$(docker create docker.io/redroid/redroid:16.0.0-latest)
echo "Created temporary container: $CONTAINER_ID"

# Extract arm64 runtime
echo "Extracting arm64 runtime..."
docker cp "$CONTAINER_ID:/system/bin/linker64" "$OLDPWD/$ASSETS_DIR/runtime/arm64-v8a/" 2>/dev/null && echo "  ✓ Copied linker64" || echo "  ✗ linker64 not found"
docker cp "$CONTAINER_ID:/system/lib64/libc.so" "$OLDPWD/$ASSETS_DIR/runtime/arm64-v8a/" 2>/dev/null && echo "  ✓ Copied libc.so" || echo "  ✗ libc.so not found"
docker cp "$CONTAINER_ID:/system/lib64/libm.so" "$OLDPWD/$ASSETS_DIR/runtime/arm64-v8a/" 2>/dev/null && echo "  ✓ Copied libm.so" || echo "  ✗ libm.so not found"
docker cp "$CONTAINER_ID:/system/lib64/libdl.so" "$OLDPWD/$ASSETS_DIR/runtime/arm64-v8a/" 2>/dev/null && echo "  ✓ Copied libdl.so" || echo "  ✗ libdl.so not found"

# Extract arm32 runtime
echo "Extracting arm32 runtime..."
docker cp "$CONTAINER_ID:/system/bin/linker" "$OLDPWD/$ASSETS_DIR/runtime/armeabi-v7a/" 2>/dev/null && echo "  ✓ Copied linker" || echo "  ✗ linker not found"
docker cp "$CONTAINER_ID:/system/lib/libc.so" "$OLDPWD/$ASSETS_DIR/runtime/armeabi-v7a/" 2>/dev/null && echo "  ✓ Copied libc.so" || echo "  ✗ libc.so not found"
docker cp "$CONTAINER_ID:/system/lib/libm.so" "$OLDPWD/$ASSETS_DIR/runtime/armeabi-v7a/" 2>/dev/null && echo "  ✓ Copied libm.so" || echo "  ✗ libm.so not found"
docker cp "$CONTAINER_ID:/system/lib/libdl.so" "$OLDPWD/$ASSETS_DIR/runtime/armeabi-v7a/" 2>/dev/null && echo "  ✓ Copied libdl.so" || echo "  ✗ libdl.so not found"

# Try to extract x86_64 runtime (may not be available)
echo "Attempting to extract x86_64 runtime..."
docker cp "$CONTAINER_ID:/system/bin/linker64" "$OLDPWD/$ASSETS_DIR/runtime/x86_64/" 2>/dev/null && echo "  ✓ Copied linker64" || echo "  ℹ x86_64 linker64 not available in container"
docker cp "$CONTAINER_ID:/system/lib64/libc.so" "$OLDPWD/$ASSETS_DIR/runtime/x86_64/" 2>/dev/null || echo "  ℹ x86_64 runtime not available, will use arm64 runtime with QEMU"

# Clean up container
docker rm "$CONTAINER_ID" >/dev/null
echo "Cleaned up temporary container"

# Return to original directory
cd "$OLDPWD"
rm -rf "$TEMP_DIR"

echo ""
echo "Asset download complete!"
echo "QEMU binaries downloaded to: $ASSETS_DIR/qemu/"
echo "Runtime libraries downloaded to: $ASSETS_DIR/runtime/"

# List what was downloaded
echo ""
echo "Downloaded QEMU binaries:"
find "$ASSETS_DIR/qemu" -type f -name "qemu-*" -exec ls -lh {} \;

echo ""
echo "Downloaded runtime libraries:"
find "$ASSETS_DIR/runtime" -type f ! -name ".gitkeep" -exec ls -lh {} \;

exit 0
